import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lex Stayz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body ><ContextProvider>{children}</ContextProvider></body>
    </html>
  );
}

function ContextProvider({ children }: { children: React.ReactNode }) {

  return <div>
    <Navbar/>
    <main>{children}</main>
  </div>
}