import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import StoreProvider from "@/components/storeProvider";
import ContextProvider from "@/components/ContextProvider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Lex Stayz",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body><StoreProvider><ContextProvider>{children}</ContextProvider></StoreProvider></body>
        </html>
    );
}

